TRANING_LOCATION = "./training_data/"
START_GENERATION = 1

DLLLOC1 = "./.exes/ai_player1.dll"
DLLLOC2 = "./.exes/ai_player2.dll"

MUTATION_RATE = 0.1
MUTATION_CHANCE = 0.5

TIME_LIMIT = 5
SAVED_TIME_MULTIPLIER = (100 / TIME_LIMIT) / 2

SAMPLE_SIZE = 100
PERSISTENT_AGENTS = 10

HEADER_SIZE = 30
